services:

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 80:80
    container_name: app_nginx
    depends_on:
      - app

  app:
    build: 
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: app

  db:
    image: mysql:latest
    ports:
      - 8765:3306
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laradocker
      MYSQL_ROOT_PASSWORD: l4raproject
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8087:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: l4raproject
    depends_on:
      - db
    container_name: app_phpmyadmin